version: '3.4'

services:
  db:
    container_name: db
    environment:
      MSSQL_SA_PASSWORD: "Aa123456!!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
     - 1433:1433

  electricitydataapp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DbConnection=Server=db;Database=ElectricityData;User Id=sa;Password=Aa123456!!;TrustServerCertificate=True;
      - Serilog:WriteTo:0:Args:connectionString=Server=db;Database=ElectricityData;User Id=sa;Password=Aa123456!!;TrustServerCertificate=True;
    ports:
      - "7777:80"
    depends_on:
      - db